#!/bin/sh
if [ $# != 2 ];then
	echo "usage  ./pack_md77 [project] [packname]"
	exit 1
fi

if [ ! -e out ];then
	echo "No out dir!!!"
	exit 1
fi	

HOMEDIR=$PWD
OUTDIR=out/target/product/$1/ 
DESDIR=$2/$2
Mode_databse1=mediatek/cgen/APDB_MT6577_S01_MAIN2.1_W10.24
Mode_databse2=mediatek/config/out/$1/modem/BPLGUInfoCustomAppSrcP_MT6577_S00_MAUI_11AMD_W12_22_SP_V27*
DATABASEDIR=$DESDIR/databases
mkdir -p $DATABASEDIR
cp $Mode_databse1 $DATABASEDIR
cp $Mode_databse2 $DATABASEDIR
cd $OUTDIR
ALLFILE=`ls -l | grep -v ^d | grep -v "zip" | awk '{print $8}'`

for i in $ALLFILE
do
	cp $i $HOMEDIR/$DESDIR
	echo "cp $i "
done
cp  *.zip $HOMEDIR/$2
cd $HOMEDIR/$DESDIR
echo "================>>begin compressing"
cd ..
tar czvfh $2.tar.gz $2
echo "================>>Compressed OK!"
rm $2 -r
cd ../../
if [ ! -e ROM ];then
	mkdir ROM
fi
mv alps/$2 ./ROM/$2
