#!/bin/bash
if [ $# != 2 ];then
	echo "usage  ./pack [project] [packname]"
	exit 1
fi

if [ ! -e alps ];then
	echo "Error exec path!!!"
	exit 1
fi

if [ ! -e alps/out ];then
	echo "No out dir!!!"
	exit 1
fi

ELINK_PROJECT=$1
TARGET=$2
HOMEDIR=$PWD
OUTDIR=alps/out/target/product/$ELINK_PROJECT/ 

if [ ! -e "$OUTDIR" ];then
	echo "$OUTDIR not found!!!"
	exit 1
fi

DESDIR=$TARGET/$TARGET
if [ -e "alps/mediatek/cgen/APDB_MT6582_S01_ALPS.JB5.TABLET.MP_" ];then
	Mode_databse1=alps/mediatek/cgen/APDB_*
	Mode_databse2=alps/mediatek/config/out/$ELINK_PROJECT/modem/BPLGUInfoCustomAppSrcP*
elif [ -e "alps/out/target/product/$ELINK_PROJECT/obj/CODEGEN/" ];then
	Mode_databse1=alps/out/target/product/$ELINK_PROJECT/obj/CODEGEN/cgen/APDB_*
	Mode_databse2=alps/out/target/product/$ELINK_PROJECT/obj/CUSTGEN/config/modem/BPLGUInfoCustomAppSrcP*
elif [ -e "alps/out/target/product/$ELINK_PROJECT/obj/CGEN/" ];then
	Mode_databse1=alps/out/target/product/$ELINK_PROJECT/obj/CGEN/APDB_*
	Mode_databse2=alps/out/target/product/$ELINK_PROJECT/system/etc/mddb/BPLGUInfoCustomAppSrcP*
fi	
	
DATABASEDIR=$DESDIR/databases
mkdir -p $DATABASEDIR
cp $Mode_databse1 $DATABASEDIR
cp $Mode_databse2 $DATABASEDIR
cd $OUTDIR
ALLFILE=`awk '/file_name/{T=$2;next}{if(/is_download/){if(/true/)print T;}}' *_Android_scatter.txt`

for i in $ALLFILE
do
	cp $i $HOMEDIR/$DESDIR
	echo "cp $i "
done
rm $HOMEDIR/$DESDIR/databases/*_ENUM
cp *_Android_scatter.txt $HOMEDIR/$DESDIR
cd $HOMEDIR/$DESDIR
#sed -i '0,/is_download/{s/true/false/}' $HOMEDIR/$DESDIR/*_Android_scatter.txt 
echo "================>>begin compressing"
cd ..
tar czvfh $TARGET.tar.gz $TARGET
echo "================>>Compressed OK!"
rm $TARGET -r
cd ../
if [ ! -e ROM ];then
	mkdir ROM
fi
mv $TARGET ./ROM/$TARGET -f
